[PHP]
memory_limit = 256M
max_execution_time = 60
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS

; Errors
display_errors = On
log_errors = On
error_reporting = E_ALL

; Date
date.timezone = America/Recife

; PCOV
pcov.directory = .
