[supervisord]
user=root
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
autostart=true
autorestart=true
command=/usr/sbin/nginx -g 'daemon off;'
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:php-fpm]
autostart=true
autorestart=true
command=/usr/local/sbin/php-fpm --nodaemonize
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:queue]
autostart=true
autorestart=true
command=/usr/local/bin/php /var/www/artisan queue:work --sleep=3 --tries=3 --max-time=3600
stderr_logfile=/var/log/supervisor/queue-worker.err.log
stdout_logfile=/var/log/supervisor/queue-worker.out.log

[program:scheduler]
autostart=true
autorestart=true
command=/usr/local/bin/php /var/www/artisan schedule:work
stderr_logfile=/var/log/supervisor/scheduler.err.log
stdout_logfile=/var/log/supervisor/scheduler.out.log

; ========================================================================================
; HORIZON CONFIG =========================================================================
; ========================================================================================
; [program:horizon]
; autostart=true
; autorestart=true
; command=/usr/local/bin/php /var/www/artisan horizon
; stderr_logfile=/var/log/supervisor/horizon.err.log
; stdout_logfile=/var/log/supervisor/horizon.out.log